# version 0 from https://github.com/Microsoft/generator-docker
version: '2'

services:
  PrimoTest:
    image: primotest:debug
    build:
      context: .
      dockerfile: Dockerfile.debug
    ports:
      - "3000:3000"
      - "5858:5858"
    volumes:
      - .:/src
    environment:
      - REMOTE_DEBUGGING
