version: '2'
services:

  hub:
    image: selenium/hub:latest
    ports:
      - "4444:4444"

  chrome:
    image: selenium/node-chrome:latest
    environment:
      VIRTUAL_HOST: node.chrome.docker
      HUB_PORT_4444_TCP_ADDR: hub
      HUB_PORT_4444_TCP_PORT: 4444
# there is commonly an initial "Connect to hub:4444 [hub/172.20.0.3] failed: Connection refused" - it picks it up on the second attempt

  nightwatch:
    image: uqlibrary/nightwatch-test
#    build: ./tests # location of Dockerfile
    environment:
      NODE_ENV: test
    volumes:
      - .:/usr/src/app
    links:
      - hub
#    entrypoint: nightwatch -c tests/nightwatch.json --tag primo --env chrome
# moved to Dockerfile CMD




# only one browser required, firefox removed

#original attempt at selenium
#  hub:
#    image: selenium/hub:latest
#    environment:
#      VIRTUAL_HOST: selenium.hub.docker
#    ports:
#      - 4444:4444

# notes:
# per https://github.com/nightwatchjs/nightwatch/wiki/Chrome-Setup
# nightwatch.json require a no-sandbox option for running in chrome in docker

# from https://github.com/mycargus/docker-grid-nightwatch/blob/master/docker-compose.yml

# need env for chrome
# https://github.com/SeleniumHQ/docker-selenium/issues/133

# more ideas
# https://github.com/tildedave/docker-nightwatch-xvfb

